version: "2"
services:
  fluent_collector:
    depends_on:
    - influxdb
    image: ${DOCKER_IMAGE_PREFIX}fluent-collector:${DOCKER_IMAGE_VERSION}
    restart: on-failure
    environment:
    - FC_SHARED_SECRET
    - FC_INFLUXDB_HOST=influxdb
    - FC_INFLUXDB_PORT=8086
    - FC_INFLUXDB_USER=${SERVICES_USER}
    - FC_INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    - FC_INFLUXDB_DATABASE=db0
    - FC_LOG_LEVEL=debug
    networks:
    - default
    - monitoring_tier
    ports:
    - ${FLUENT_COLLECTOR_PORT}:24284
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${DOCKER_IMAGE_VERSION}
#    logging:
#      driver: json-file

  influxdb:
    image: influxdb:latest
    restart: on-failure
    environment:
#    - INFLUXDB_ADMIN_ENABLED=true
#    - INFLUXDB_ADMIN_USER=admin
#    - INFLUXDB_ADMIN_PASSWORD=Secret123
    - INFLUXDB_USER=${SERVICES_USER}
    - INFLUXDB_USER_PASSWORD=${INFLUXDB_PASSWORD}
    - INFLUXDB_DB=db0
    volumes:
    - influxdb_data:/var/lib/influxdb
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${DOCKER_IMAGE_VERSION}

  chronograf:
    depends_on:
    - influxdb
    image: chronograf:latest
    restart: on-failure
#    environment:
#    - INFLUXDB_URL=http://influxdb:8086
#    - INFLUXDB_USERNAME=${SERVICES_USER}
#    - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
#    - TOKEN_SECRET=xyz
    volumes:
    - chronograf_config:/var/lib/chronograf
    ports:
    - ${CHRONOGRAF_PORT}:8888
    cpu_shares: 256
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${DOCKER_IMAGE_VERSION}

networks:
  monitoring_tier:
    external: true

volumes:
  chronograf_config:
    driver: local

  influxdb_data:
    driver: local
