version: "2"
services:
  fluent_collector:
    image: ${DOCKER_IMAGE_PREFIX}fluent-collector:${DOCKER_IMAGE_VERSION}
    restart: on-failure
    environment:
    - FC_SHARED_SECRET
    - FC_MONGO_HOST=mongo
    - FC_MONGO_PORT=27017
    - FC_MONGO_USER=${SERVICES_USER}
    - FC_MONGO_PASSWORD=${MONGO_PASSWORD}
    - FC_MONGO_DATABASE=admin
    - FC_MONGO_COLLECTION=logs
    networks:
    - default
    - monitoring_tier
    ports:
    - ${FLUENT_COLLECTOR_PORT}:24284
    labels:
    - version=${DOCKER_IMAGE_VERSION}

  mongo:
    image: mongo:latest
    restart: on-failure
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${SERVICES_USER}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
    - mongo_config:/data/configdb
    - mongo_data:/data/db
    labels:
    - version=${DOCKER_IMAGE_VERSION}

  mongo_express:
    depends_on:
    - mongo
    image: mongo-express:latest
    restart: on-failure
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongo
    - ME_CONFIG_MONGODB_PORT=27017
    - ME_CONFIG_MONGODB_ADMINUSERNAME=${SERVICES_USER}
    - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
    - ME_CONFIG_BASICAUTH_USERNAME=${SERVICES_USER}
    - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
    ports:
    - ${MONGO_EXPRESS_PORT}:8081
    labels:
    - version=${DOCKER_IMAGE_VERSION}

networks:
  monitoring_tier:
    external: true

volumes:
  mongo_config:
    driver: local

  mongo_data:
    driver: local
