version: "2"
services:
  web:
    depends_on:
      - mailhog

  cron:
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025

  minio:
    ports:
      - ${MINIO_PORT}:9000

  mysql:
    ports:
      - ${MYSQL_PORT}:3306
