version: "2"
services:
  web:
    depends_on:
      - mailhog

  cron:
    depends_on:
      - mailhog

  adminer:
    image: adminer:latest
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - mysql

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025

  minio:
    ports:
      - ${MINIO_PORT}:9000

  mysql:
    ports:
      - ${MYSQL_PORT}:3306
