version: "2"
services:
  ci:
    image: damlys/webdock-ci:${CI_VERSION}
    ports:
      - ${CI_DASHBOARD_PORT}:8080
      - ${CI_PORT}:50000
    volumes:
      - ci_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  ci_data:
