version: "2"
services:
  backend:
    image: ${BACKEND_IMAGE}:current
    ports:
      - ${BACKEND_PORT}:80
    networks:
      - backend
    links:
      - mysql
      - redis
    env_file:
      - .env

  backend_cron:
    image: ${BACKEND_IMAGE}:current
    networks:
      - backend
    links:
      - mysql
      - redis
    env_file:
      - .env
    command: sh -c "/codebase/bin/cron-container-startup-command.sh"

  frontend:
    image: ${FRONTEND_IMAGE}:current
    ports:
      - ${FRONTEND_PORT}:80
    networks:
      - frontend
    env_file:
      - .env

  mysql:
    image: mysql:latest
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    image: redis:latest
    networks:
      - backend
    command: redis-server --requirepass ${REDIS_PASSWORD}

networks:
  backend:
  frontend:
