version: "2"
services:
  backend_base:
    image: ${BACKEND_IMAGE}-base:current
    build:
      context: ./backend/
      dockerfile: Dockerfile.base

  backend:
    depends_on:
      - backend_base
    build:
      context: ./backend/
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BACKEND_IMAGE}-base
    volumes:
      - ./backend/codebase/:/codebase/

  backend_cron:
    volumes:
      - ./backend/codebase/:/codebase/

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/codebase/public/:/codebase/public/

  frontend_node:
    image: ${FRONTEND_IMAGE}-node:current
    build:
      context: ./frontend/
      dockerfile: Dockerfile.node
    volumes:
      - ./frontend/codebase/:/codebase/
