version: "2"
services:
  backend:
    links:
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025
    networks:
      - backend

  mysql:
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - backend
    links:
      - mysql
    environment:
      PMA_HOSTS: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
