version: "2"
services:
  backend_base:
    image: ${COMPOSE_PROJECT_NAME}/backend_base:current
    build:
      context: ./backend_base/
      dockerfile: Dockerfile

  backend:
    depends_on:
      - backend_base
    build:
      context: ./backend/
      dockerfile: Dockerfile
      args:
        BASE_IMAGE_NAME: ${COMPOSE_PROJECT_NAME}/backend_base
        BASE_IMAGE_TAG: current
    volumes:
      - ./backend/codebase/:/codebase/

  backend_cron:
    volumes:
      - ./backend/codebase/:/codebase/

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/codebase/public/:/codebase/public/

  frontend_node:
    image: ${COMPOSE_PROJECT_NAME}/frontend_node:current
    build:
      context: ./frontend_node/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/codebase/:/codebase/
