version: '2'
services:

#############################
### Application container
#############################

    application:
        image: ${HUB_USERNAME}/${HUB_REPOSITORY_PREFIX}-application:0.0.1
        depends_on:
            - storage
        links:
            - mariadb
            - redis
        volumes_from:
            - storage
        working_dir: /application/
        environment:
            - APP_HTTP_AUTH_BASIC

            - APP_AVAILABLE_FRONT_CONTROLLERS
            - APP_DEFAULT_FRONT_CONTROLLER
            - APP_DEBUG_FRONT_CONTROLLERS_ACCESS

            - APP_MARIADB_HOST=mariadb
            - APP_MARIADB_PORT=3306
            - APP_MARIADB_USER=${MARIADB_USER}
            - APP_MARIADB_PASSWORD=${MARIADB_PASSWORD}
            - APP_MARIADB_DATABASE=${MARIADB_DATABASE}

            - APP_REDIS_HOST=redis
            - APP_REDIS_PORT=6379
            - APP_REDIS_PASSWORD=${REDIS_PASSWORD}

            - APP_SMTP_HOST
            - APP_SMTP_PORT
            - APP_SMTP_USER
            - APP_SMTP_PASSWORD

            - APP_STORAGE_ROOT=/storage/

#############################
### Storage container
#############################

    storage:
        image: ${HUB_USERNAME}/${HUB_REPOSITORY_PREFIX}-storage:0.0.1

#############################
### MariaDB container
#############################

    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MYSQL_USER: ${MARIADB_USER}
            MYSQL_PASSWORD: ${MARIADB_PASSWORD}
            MYSQL_DATABASE: ${MARIADB_DATABASE}

#############################
### Redis container
#############################

    redis:
        image: redis:latest
        command: redis-server --requirepass ${REDIS_PASSWORD}
