version: "2"
services:
  api:
    image: ${COMPOSE_PROJECT_NAME}/api:current
    networks:
      - backend
    links:
      - mysql
      - redis
    env_file:
      - .env

  api_cron:
    image: ${COMPOSE_PROJECT_NAME}/api:current
    networks:
      - backend
    links:
      - mysql
      - redis
    env_file:
      - .env
    command: ["--start-cron"]

  mysql:
    image: mysql:latest
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    image: redis:latest
    networks:
      - backend
    command: ["--requirepass", "${REDIS_PASSWORD}"]

  spa:
    image: ${COMPOSE_PROJECT_NAME}/spa:current
    networks:
      - frontend
    env_file:
      - .env

networks:
  backend:
  frontend:
