version: "2"
services:
  api:
    depends_on:
      - api_fundament
    build:
      context: ./api/
      dockerfile: Dockerfile
      args:
        BASE_IMAGE_NAME: ${COMPOSE_PROJECT_NAME}/api_fundament
        BASE_IMAGE_TAG: current
    volumes:
      - ./api/codebase/:/codebase/

  api_cron:
    volumes:
      - ./api/codebase/:/codebase/

  api_fundament:
    image: ${COMPOSE_PROJECT_NAME}/api_fundament:current
    build:
      context: ./api_fundament/
      dockerfile: Dockerfile

  spa:
    build:
      context: ./spa/
      dockerfile: Dockerfile
    volumes:
      - ./spa/codebase/public/:/codebase/public/

  spa_node:
    image: ${COMPOSE_PROJECT_NAME}/spa_node:current
    build:
      context: ./spa_node/
      dockerfile: Dockerfile
    volumes:
      - ./spa/codebase/:/codebase/
