version: '2'
services:

#############################
### PHP container
#############################

    php:
        build:
            args:
                INSTALL_XDEBUG: "yes"
        links:
            - mailhog
        environment:
            - XDEBUG_REMOTE_CONNECT_BACK
            - XDEBUG_REMOTE_HOST
            - XDEBUG_REMOTE_PORT
            - XDEBUG_IDE_KEY

#############################
### MariaDB container
#############################

    mariadb:
        ports:
            - ${MARIADB_PORT}:3306

#############################
### phpMyAdmin container
#############################

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - mariadb
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            PMA_HOSTS: mariadb
            PMA_USER: ${MARIADB_USER}
            PMA_PASSWORD: ${MARIADB_PASSWORD}

#############################
### MailHog container
#############################

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - ${MAILHOG_PORT}:8025
