version: "2"
services:
  http_server:
    image: ${DOCKER_IMAGE_PREFIX}web-client:${DOCKER_IMAGE_VERSION}
    restart: on-failure
    env_file:
    - .env
    environment:
    - WEBCLIENT_VERSION=${DOCKER_IMAGE_VERSION}
    - WEBCLIENT_HTTP_WORKERS_COUNT=5
    cpu_shares: 1024
    mem_limit: 64mb
    memswap_limit: 0
    labels:
    - version=${DOCKER_IMAGE_VERSION}
