version: "2"
services:
  http_server:
    image: "damlys/webdock-web-client:${TAG}"
    env_file:
      - .env
    environment:
      - "WEBCLIENT_VERSION=${TAG}"
      - WEBCLIENT_HTTP_WORKERS_COUNT=5
    mem_limit: 64m
    memswap_limit: 0
