version: "2"
services:
  http_server:
    image: "damlys/webdock-web-client:${WEBCLIENT_VERSION}"
    env_file:
      - ./../.env
    environment:
      - WEBCLIENT_HTTP_WORKERS_COUNT=5
    mem_limit: 64m
    memswap_limit: 0
