version: "2"
services:
  http_server:
    volumes:
    - ./../image/app/public/:/opt/app/public/

  assets_builder:
    depends_on:
    - fluent_forwarder
    image: ${DOCKER_IMAGE_PREFIX}web-assets-builder:0.0.1-example
    command: ["sleep", "infinity"]
    volumes:
    - global_npm_cache:/var/cache/npm/
    - ./../image/app/:/opt/app/
    working_dir: /opt/app/
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:${FLUENT_FORWARDER_PORT}

volumes:
  global_npm_cache:
    external: true
