version: "2"
services:
  web:
    volumes:
      - composer_cache:/var/cache/composer
      - ./app/:/app/

  cron:
    volumes:
      - composer_cache:/var/cache/composer
      - ./app/:/app/

volumes:
  composer_cache:
