version: "2"
services:
  web:
    image: damlys/webdock-php-web-server:${APP_VERSION}
    depends_on:
      - mailhog
      - mysql
      - rabbitmq
      - redis
    environment:
      - APP_MYSQL_HOST=mysql
      - APP_RABBITMQ_HOST=rabbitmq
      - APP_REDIS_HOST=redis
      - APP_SMTP_HOST=mailhog
      - APP_SMTP_PORT=1025
    env_file: .env

  cron:
    image: damlys/webdock-php-web-server:${APP_VERSION}
    depends_on:
      - mailhog
      - mysql
      - rabbitmq
      - redis
    environment:
      - APP_MYSQL_HOST=mysql
      - APP_RABBITMQ_HOST=rabbitmq
      - APP_REDIS_HOST=redis
      - APP_SMTP_HOST=mailhog
      - APP_SMTP_PORT=1025
    env_file: .env
    command: ["--start-cron"]

  mailhog:
    image: mailhog/mailhog:latest

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${APP_MYSQL_USER}
      - MYSQL_PASSWORD=${APP_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${APP_MYSQL_DATABASE}

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${APP_RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${APP_RABBITMQ_PASSWORD}

  redis:
    image: redis:latest
    command: ["--requirepass", "${APP_REDIS_PASSWORD}"]
