version: "2"
services:
  app:
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025

  mysql:
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mysql
    environment:
      PMA_HOSTS: mysql
      PMA_USER: ${PHPMYADMIN_USER}
      PMA_PASSWORD: ${PHPMYADMIN_PASSWORD}
