version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - composer_cache:/var/cache/composer
      - ./app/:/app/

  cron:
    volumes:
      - composer_cache:/var/cache/composer
      - ./app/:/app/

volumes:
  composer_cache:
