version: "2"
services:
  jenkins_master:
    depends_on:
    - jenkins_slave
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - FROM=${DOCKER_IMAGE_PREFIX}jenkins-master:${DOCKER_IMAGE_VERSION}
      - DOCKER_GID=${HOST_DOCKER_GID}
    image: ${COMPOSE_PROJECT_NAME}_jenkins_master:${DOCKER_IMAGE_VERSION}
    restart: on-failure
    environment:
    - JENKINS_HOME=/var/jenkins/master/
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/jenkins/:/var/jenkins/
    working_dir: /var/jenkins/master/
    ports:
    - ${JENKINS_DASHBOARD_PORT}:8080

  jenkins_slave:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - FROM=${DOCKER_IMAGE_PREFIX}jenkins-slave:${DOCKER_IMAGE_VERSION}
      - DOCKER_GID=${HOST_DOCKER_GID}
    image: ${COMPOSE_PROJECT_NAME}_jenkins_slave:${DOCKER_IMAGE_VERSION}
    restart: on-failure
    environment:
    - JENKINS_AGENT_WORKDIR=/var/jenkins/slave/
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/jenkins/slave/:/var/jenkins/slave/
    working_dir: /var/jenkins/slave/
    # This is a fake slave. It prevents deleting slave Docker image during artifacts cleanup.
    # You have to configure `docker-plugin` to use slaves correctly.
    entrypoint: []
    command: ["sleep", "infinity"]
