version: "2"
services:
  app_web:
    volumes:
      - ./app/public/:/app/public/

  node:
    image: damlys/webdock-node:example
    volumes:
      - npm_cache:/var/cache/npm
      - ./app/:/app/
    working_dir: /app/

volumes:
  npm_cache:
