version: "2"
services:
  cgi_server:
    depends_on:
    - minio
    - mysql
    - rabbitmq
    - redis

  task_scheduler:
    depends_on:
    - minio
    - mysql
    - rabbitmq
    - redis

  example_worker:
    depends_on:
    - minio
    - mysql
    - rabbitmq
    - redis

  minio:
    depends_on:
    - fluent_forwarder
    image: minio/minio:latest
    command: ["minio", "server", "/data"]
    restart: on-failure
    environment:
    - MINIO_ACCESS_KEY=${BACKING_SERVICES_USER}
    - MINIO_SECRET_KEY=${MINIO_PASSWORD}
    volumes:
    - minio_data:/data
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:${FLUENT_FORWARDER_PORT}

  minio_constructor:
    depends_on:
    - fluent_forwarder
    - minio
    image: minio/mc:latest
    entrypoint: >
      sh -c "
        /usr/bin/mc config host add myminioserver http://minio:9000 '${BACKING_SERVICES_USER}' '${MINIO_PASSWORD}';
        /usr/bin/mc mb myminioserver/myminiobucket;
        /usr/bin/mc policy download myminioserver/myminiobucket;
        exit 0
      "
    restart: on-failure
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:${FLUENT_FORWARDER_PORT}

  mysql:
    depends_on:
    - fluent_forwarder
    image: mysql:5
    restart: on-failure
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_USER=${BACKING_SERVICES_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=db0
    volumes:
    - mysql_data:/var/lib/mysql
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:${FLUENT_FORWARDER_PORT}

  rabbitmq:
    depends_on:
    - fluent_forwarder
    image: rabbitmq:latest
    restart: on-failure
    environment:
    - RABBITMQ_DEFAULT_USER=${BACKING_SERVICES_USER}
    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:${FLUENT_FORWARDER_PORT}

  redis:
    depends_on:
    - fluent_forwarder
    image: redis:latest
    command: ["--requirepass", "${REDIS_PASSWORD}"]
    restart: on-failure
    volumes:
    - redis_data:/data
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:${FLUENT_FORWARDER_PORT}

volumes:
  minio_data:
    driver: local

  mysql_data:
    driver: local

  rabbitmq_data:
    driver: local

  redis_data:
    driver: local
