version: "2"
services:
  minio:
    ports:
    - ${MINIO_PORT}:9000

  mysql:
    ports:
    - ${MYSQL_PORT}:3306

  phpmyadmin:
    depends_on:
    - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: on-failure
    environment:
    - PMA_HOST=mysql
    - PMA_PORT=3306
    ports:
    - ${PHPMYADMIN_PORT}:80
    labels:
    - version=${DOCKER_IMAGE_VERSION}

  rabbitmq:
    image: rabbitmq:management
    ports:
    - ${RABBITMQ_MANAGEMENT_PORT}:15672

  redis_commander:
    depends_on:
    - redis
    image: rediscommander/redis-commander:latest
    restart: on-failure
    environment:
    - HTTP_USER=${BACKING_SERVICES_USER}
    - HTTP_PASSWORD=${REDIS_PASSWORD}
    - REDIS_HOSTS=session:redis:6379:0:${REDIS_PASSWORD},cache:redis:6379:1:${REDIS_PASSWORD}
    ports:
    - ${REDIS_COMMANDER_PORT}:8081
    labels:
    - version=${DOCKER_IMAGE_VERSION}
