version: "2"
services:
  migrator:
    depends_on:
    - mailhog

  cgi_server:
    depends_on:
    - mailhog

  task_scheduler:
    depends_on:
    - mailhog

  example_worker:
    depends_on:
    - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    entrypoint: >
      sh -c "
        echo \"${BACKING_SERVICES_USER}:$$(MailHog bcrypt '${MAILHOG_PASSWORD}')\" > /home/mailhog/htpasswd;
        MailHog -auth-file=/home/mailhog/htpasswd
      "
    restart: on-failure
    ports:
    - ${MAILHOG_PORT}:8025
    cpu_shares: 256
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${DOCKER_IMAGE_VERSION}
