version: "2"
services:
  cgi_server:
    depends_on:
    - mailhog

  task_scheduler:
    depends_on:
    - mailhog

  example_worker:
    depends_on:
    - mailhog

  mailhog:
    depends_on:
    - fluent_forwarder
    image: mailhog/mailhog:latest
    entrypoint: >
      sh -c "
        echo \"${BACKING_SERVICES_USER}:$$(MailHog bcrypt '${MAILHOG_PASSWORD}')\" > /home/mailhog/htpasswd;
        MailHog -auth-file=/home/mailhog/htpasswd
      "
    restart: on-failure
    ports:
    - ${MAILHOG_PORT}:8025
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:${FLUENT_FORWARDER_PORT}

  minio:
    ports:
    - ${MINIO_PORT}:9000

  mysql:
    ports:
    - ${MYSQL_PORT}:3306

  phpmyadmin:
    depends_on:
    - fluent_forwarder
    - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: on-failure
    environment:
    - PMA_HOST=mysql
    - PMA_PORT=3306
    ports:
    - ${PHPMYADMIN_PORT}:80
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:${FLUENT_FORWARDER_PORT}

  rabbitmq:
    image: rabbitmq:management
    ports:
    - ${RABBITMQ_MANAGEMENT_PORT}:15672

  redis_commander:
    depends_on:
    - fluent_forwarder
    - redis
    image: rediscommander/redis-commander:latest
    restart: on-failure
    environment:
    - HTTP_USER=${BACKING_SERVICES_USER}
    - HTTP_PASSWORD=${REDIS_PASSWORD}
    - REDIS_HOSTS=session:redis:6379:0:${REDIS_PASSWORD},cache:redis:6379:1:${REDIS_PASSWORD}
    ports:
    - ${REDIS_COMMANDER_PORT}:8081
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:${FLUENT_FORWARDER_PORT}
