version: "2"
services:
  cgi_server:
    volumes:
      - global_composer_cache:/var/cache/composer/
      - ./../image/app/:/opt/app/

  http_server:
    volumes:
      - global_composer_cache:/var/cache/composer/
      - ./../image/app/:/opt/app/

  task_scheduler:
    volumes:
      - global_composer_cache:/var/cache/composer/
      - ./../image/app/:/opt/app/

  example_worker:
    volumes:
      - global_composer_cache:/var/cache/composer/
      - ./../image/app/:/opt/app/

  application_builder:
    image: "${DOCKER_IMAGE_PREFIX}php-web-server-foundation:0.0.1-example"
    command: ["sleep", "infinity"]
    volumes:
      - global_composer_cache:/var/cache/composer/
      - ./../image/app/:/opt/app/
    working_dir: /opt/app/

volumes:
  global_composer_cache:
    external: true
